### ISSUE TITLE
404 error trying to download latest release v1.2.0

### ISSUE THREAD

**Issue by jumpingbrowntrout** [ps2dev/ps2client#11]
Hi, would it be possible to investigate this issue?
The link returns a 404 error which is a github published 404 page
https://github.com/ps2dev/ps2client/releases/tag/%22refs%2Ftags%2Fv1.2.0%22

**Comment by AKuHAK** [comment]
This is fixed in #10

**Comment by jumpingbrowntrout** [comment]
Awesome @AKuHAK is there a new url/direct link?

**Comment by AKuHAK** [comment]
It is better to wait until this PR will be merged. If you wish you can download artifacts from actions tab.
https://github.com/ps2dev/ps2client/actions/runs/520597832
Scroll down until you see the attachments.

**Comment by AKuHAK** [comment]
> Awesome @AKuHAK is there a new url/direct link?

And finally latest development build is accessible here:
https://github.com/ps2dev/ps2client/releases/tag/latest

**Comment by fjtrujy** [comment]
Closing as this issue is being solved with `v1.3.0`
