### ISSUE TITLE
ps2client doesn't seem to write anything on command console

### ISSUE THREAD

**Issue by israpps** [ps2dev/ps2client#17]
Not sure if it's a problem of my setup or a problem of the program itself...

but I can't catch any printf with ps2client...

tested `listen` with in-game debug OPL (latest beta) and nothing

execee works too but no printf at all on console

any idea?

**Comment by Wellinator** [comment]
Same here the termial keeps blank after execee command.

**Comment by israpps** [comment]
> Same here the termial keeps blank after execee command.

The issue was partially fixed after installing [this](https://github.com/nmap/nmap) to obtain netcat 

However, now printf is truncated...

And I haven't found a solution yet

**Comment by Wellinator** [comment]
Thx! I'll try it

**Comment by fjtrujy** [comment]
I think this issue is now solved, please reopen it if it is still not working for you.
Cheers.
