### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by shooter0106** [ps2dev/ps2client#5]
Hello!
While building a ps2toolchain i see an a error:
```
src/ps2link.c: In function ‘ps2link_connect’:
src/ps2link.c:50:44: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
   if (console_socket > 0) { pthread_create(&console_thread_id, NULL, ps2link_thread_console, (void *)&console_thread_id); }
                                            ^~~~~~~~~~~~~~~~~~                                ~~~~~~~~~~~~~~~~~~~~~~~~~~
src/ps2link.c:56:44: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
   if (request_socket > 0) { pthread_create(&request_thread_id, NULL, ps2link_thread_request, (void *)&request_thread_id); }
                        
```
Seems like a building problem on a newer host system toolchain. I have a Debian Buster with GCC version 8.3 installed from repository.

What i can make with this? Thanks!

**Comment by sp193** [comment]
The title says that "compilation failed", but you posted a warning instead. A compiler warning is generally not a fatal error. There might be something that needs to be done about that warning, but is there actually an error that you want to bring up?

**Comment by shooter0106** [comment]
Yeah, you are a totally right. It's not a compilation problem: build script is silently finish their job, and I think is last compiler message is an error. Maybe build script needs explicitly notify about successfuly finish, this is confused me.

Thanks for your job. And sorry me for wasitng your time.
